author: OpenKitten
author_url: https://github.com/OpenKitten
module_version: development
github_url: https://github.com/OpenKitten/Meow
copyright: 'Copyright © 2016 Robbert Brandsma & Joannis Orlandos'
readme: DocsIndex.md
documentation: Guides/*.md
include: 
- Sources/Meow
